defi-wonderland/smock

- src/factories/ethers-interface.ts
- src/types.ts
- test/unit/fake/initialization.spec.ts
Added more initialization tests as well.
I wanted to do this because in order to `fake` the `IUniswapV2Pair` I needed to do:
`await lopt.fake(IUniswapV2Pair.abi);`
instead of:
`await lopt.fake(IUniswapV2Pair);`
This happens because the OZ V2 interface doesn't have all the corresponding contract parameters, but we just care about the abi...
> refactor: simplied interface search

- .github/workflows/canary.yml
- .github/workflows/release.yml
- README.rst
- package.json
Convert README from rst to md before publishing to npm. We need to do this because npm doesn't support rst
> feat: converting readme to md in publish

- src/factories/smock-contract.ts
- src/index.ts
- src/sandbox.ts
- test/contracts/mock/Librarian.sol
- test/contracts/mock/TestLibrary.sol
- test/unit/mock/initialization.spec.ts
Mocks now receive the same arguments as `ethers.getContractFactory` and it forwards them to the real function
> feat: mocks can be deployed with libs

- src/chai-plugin/types.ts
- src/index.ts
Types were not being correctly exported when using matchers. Very minor fix but makes the matchers actually useful when using TypeScript.
> fix: correctly export assertion types

- src/types.ts
- test/contracts/mock/Counter.sol
- test/unit/mock/initialization.spec.ts
Minor update to the MockContractFactory type to guarantee that `.connect` will return a `MockContractFactory` type.
**Metadata**
- Fixes #63
> fix: have connect function return mock factory

- package.json
Minor fix. Moves `@nomiclabs/ethereumjs-vm` into dependencies since it's required (for now) and hardhat doesn't necessarily bundle it anymore.
**Metadata**
- Fixes #70
> fix: move ethereumjs-vm into deps

- src/factories/smock-contract.ts
- test/unit/mock/initialization.spec.ts
Slightly updates the way we create mock contract factories so that `.connect` also returns a mock contract factory.
> fix: make sure connect returns the correct factory instance

- src/factories/ethers-interface.ts
- test/contracts/watchable-function-logic/IPartialReceiver.sol
- test/unit/fake/initialization.spec.ts
Slightly modifies the spec generation process so that we can successfully generate fakes from interfaces.
**Metadata**
- Fixes #77
> feat: support fakes from interfaces

- src/types.ts
Adds a call signature to programmable functions so we can actually trigger functions attached to `MockContract`s. I ran into this bug while trying to use smock v2 as part of a unit test.
> fix: add call signature to programmable functions

- src/logic/programmable-function-logic.ts
- test/contracts/mock/Counter.sol
- test/unit/mock/call-through.spec.ts
Tiny fix + test that allows mocks/fakes to override functions that revert. 
**Metadata**
- Fixes #83
> fix: allow mocks to override reverting functions

- docs/source/mocks.rst
- src/factories/smock-contract.ts
- src/logic/editable-storage-logic.ts
- src/types.ts
- test/unit/mock/editable-storage-logic.spec.ts
Adding a new function for mock contracts. With setVariables mocks will
be able to edit multiple internal variables at once.
- Fixes #111
> feat: add setVariables function

- src/utils/storage.ts
- test/unit/mock/editable-storage-logic.spec.ts
Adds support for large bytes array or string > 31 bytes based on the solidity docs 
- Fixes #30
> feat: add support for large bytes > 31 bytes

- docs/source/fakes.rst
- docs/source/mocks.rst
- src/chai-plugin/matchers.ts
- src/chai-plugin/types.ts
- src/factories/smock-contract.ts
- src/logic/watchable-function-logic.ts
- src/types.ts
- test/contracts/programmable-function-logic/Delegator.sol
- test/unit/programmable-function-logic/type-handling.spec.ts
- test/unit/watchable-function-logic/misc.spec.ts
Fixes #131
* Adds support to delegated calls in both fakes and mocks
* Adds custom assertion `expect(myFake.myFunction).to.be.delegatedFrom(myProxy.address)`
Canary version: 0.0.0-9be6e836
> fix: delegated calls support

- docs/source/mocks.rst
- src/factories/smock-contract.ts
- src/logic/readable-storage-logic.ts
- src/types.ts
- src/utils/hex-utils.ts
- src/utils/storage.ts
- test/contracts/mock/StorageGetter.sol
- test/unit/mock/editable-storage-logic.spec.ts
- test/unit/mock/readable-storage-logic.spec.ts
This commit introduces a new function for mock contracts. With `getVariable` you can view an internal variable's value.
**Approach**
A rough idea of how I approached this problem is:
1) I get an array of slot keys using `getVariableStorageSlots` that represent the position of the variable's value.
2) I get the values that are stored in those slots using the `vmManager.getContractStorage` function and providing the contract address and the appropriate slot key.
3) I decoded the values using the `decodeVariable` function and providing all the values from the above step which results in the variable's value
**Metadata**
- Fixes #14
> feat: add getVariable function

- docs/source/fakes.rst
- src/chai-plugin/matchers.ts
- src/chai-plugin/types.ts
- src/factories/smock-contract.ts
- src/logic/watchable-function-logic.ts
- src/types.ts
- test/contracts/watchable-function-logic/Receiver.sol
- test/unit/watchable-function-logic/call-arguments.spec.ts
- test/unit/watchable-function-logic/type-handling.spec.ts
Adds full support for call `msg.value`, see changed documentation in order to see new implemented methods
**Metadata**
- Fixes #114
> feat: added support for call value

- src/utils/storage.ts
- test/contracts/mock/StorageGetter.sol
- test/unit/mock/editable-storage-logic.spec.ts
- test/unit/mock/readable-storage-logic.spec.ts
Add support for arrays on `setVariable` for Mock contracts.
**Metadata**
- Fixes #31
> feat: arrays support for setVariable

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- package.json
- src/factories/smock-contract.ts
- src/logic/programmable-function-logic.ts
- src/observable-vm.ts
- src/sandbox.ts
- src/types.ts
- src/utils/hardhat.ts
- yarn.lock
- Updated hardhat to `2.11.0`
- Updated typescript to `4.5.2`
- Added deps
`"@nomicfoundation/ethereumjs-evm": "^1.0.0-rc.3"`
`"@nomicfoundation/ethereumjs-util": "^8.0.0-rc.3"`
`"@nomicfoundation/ethereumjs-vm": "^6.0.0-rc.3"`
`"@types/debug": "^4.1.4"`
`"@types/readable-stream"`
- Fixed various issues
- Removed `beforeTx` event listener since ethereumjs-evm doesn't support it (https://github.com/NomicFoundation/ethereumjs-vm/blob/1c39af3bd71be277e3d613f9659234f82dc4e341/packages/evm/src/types.ts#L216-L221)
- Update github workflow node version to `14.X`
**Metadata**
- Fixes #153
> feat: update ethereumjs vm and hardhat

- CHANGELOG.md
- package.json
- Updated hardhat to `2.11.0`
- Updated typescript to `4.5.2`
- Added deps
`"@nomicfoundation/ethereumjs-evm": "^1.0.0-rc.3"`
`"@nomicfoundation/ethereumjs-util": "^8.0.0-rc.3"`
`"@nomicfoundation/ethereumjs-vm": "^6.0.0-rc.3"`
`"@types/debug": "^4.1.4"`
`"@types/readable-stream"`
- Fixed various issues
- Removed `beforeTx` event listener since ethereumjs-evm doesn't support it (https://github.com/NomicFoundation/ethereumjs-vm/blob/1c39af3bd71be277e3d613f9659234f82dc4e341/packages/evm/src/types.ts#L216-L221)
- Update github workflow node version to `14.X`
**Metadata**
- Fixes #153
> chore(release): 2.3.0

- src/utils/storage.ts
- test/contracts/mock/StorageGetter.sol
- test/unit/mock/editable-storage-logic.spec.ts
- test/unit/mock/readable-storage-logic.spec.ts
In mappings using the function `padNumHexSlotValue` causes a bug on hashes of bytes32 as a key. We should be using the function `padBytesHexSlotValue` which is targeted for bytes values.
A different approach from #160 although it fixes the issue I believe that the usage of the `padNumHexSlotValue` is incorrectly when we deal with `bytes` type as key
> fix: bug with usage of padNumHexSlotValue

- README.md
- package.json
This changes the output variant of markdown to gfm, github-flavored markdown.
A clear and concise description of the features you're adding in this pull request.
**Metadata**
- Fixes #[Link to Issue]
> fix: change markdown output variant

- src/utils/hardhat.ts
The next version of Hardhat is going to change how `hre.network.provider` works. The provider will now be lazily initialized, as part of a new feature that lets plugin authors extend the provider behavior.
That change will break smock, but this PR fixes that. I tested it both with the new (unrealesed) changes and with the current version, and in both cases it works fine.
> fix: initialize hardhat provider
