defi-wonderland/smock

docs/source/fakes.rst
docs/source/index.rst
docs/source/todo.rst
src/factories/lopt-contract.ts
src/logic/programmable-function-logic.ts
src/types.ts
test/unit/programmable-function-logic/revert.spec.ts
test/unit/programmable-function-logic/type-handling.spec.ts

feat: fallback function support

---

CHANGELOG.md
hardhat.config.ts
package.json
src/chai-plugin/formatter.ts
src/factories/ethers-interface.ts
src/factories/lopt-contract.ts
src/index.ts
src/logic/programmable-function-logic.ts
src/logic/watchable-function-logic.ts
src/sandbox.ts
src/types.ts
src/utils/hardhat.ts
src/utils/wallet.ts
test/unit/fake/initialization.spec.ts
test/unit/mock/call-through.spec.ts
test/unit/programmable-function-logic/at-call.spec.ts
test/unit/programmable-function-logic/reset.spec.ts
test/unit/programmable-function-logic/revert.spec.ts
test/unit/programmable-function-logic/type-handling.spec.ts
test/unit/watchable-function-logic/at-call.spec.ts
test/unit/watchable-function-logic/call-arguments.spec.ts
test/unit/watchable-function-logic/call-count.spec.ts
test/unit/watchable-function-logic/call-order.spec.ts
test/unit/watchable-function-logic/misc.spec.ts
test/unit/watchable-function-logic/type-handling.spec.ts
tsconfig.json
yarn.lock

Moved most of the dependencies to be peer dependencies

refactor: reduce library size

---

docs/requirements.txt
docs/source/_static/css/base.css
docs/source/conf.py
docs/source/index.rst
docs/source/migrations/v1-to-v2.rst

* added docs emoji support as well

docs: added v1 to v2 migration guide

---

README.md

Updates the primary README with:
- Some minor edits
- A new "License" section
- A specific section for "why you should use smock"
I think major remaining TODOs in the README are:

docs: update primary readme

---

docs/source/index.rst
docs/source/mocks.rst
src/factories/smock-contract.ts
src/index.ts
src/sandbox.ts
src/types.ts
test/unit/mock/call-through.spec.ts
test/unit/mock/editable-storage-logic.spec.ts

fix: preserving factory deploy argument types

---

.github/workflows/release.yml

Adds a basic workflow file for automatically publishing packages to npm whenever `package.json => version` changes.

feat: add workflow file for auto publish to npm

---

LICENSE
package.json

Minor updates to `package.json` and `LICENSE`.

chore: update package.json in prep for 2.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Adds new templates for issues and pull requests to simplify and standardize issue/pr creation.

feat: add issue and PR templates

---

src/sandbox.ts
src/utils/storage.ts

Added Github issue links to feature errors

docs: added github issue link to feature errors

---

.github/workflows/canary.yml

Adds a workflow for doing canary releases. I think this works.

feat: workflow for canary releases

---

docs/source/fakes.rst

docs: added wallet to fakes

---

docs/source/fakes.rst
src/factories/smock-contract.ts
src/logic/programmable-function-logic.ts
src/logic/watchable-function-logic.ts
src/types.ts
test/contracts/programmable-function-logic/PickyReturner.sol
test/unit/programmable-function-logic/when-called-with.spec.ts

Revert or return a pre-programmed value based on the call arguments

feat: whenCalledWith

---

src/index.ts
test/unit/fake/initialization.spec.ts

fix: reinit sandbox is case of an evm reset

---

src/factories/smock-contract.ts
src/types.ts

feat: propagate types when using connect function

---

src/factories/smock-contract.ts
test/unit/fake/initialization.spec.ts
test/unit/mock/initialization.spec.ts

Added wallet to mocks
**Metadata**
- Fixes https://github.com/defi-wonderland/smock/issues/93

feat: added wallet to mocks

---

src/logic/editable-storage-logic.ts

Add type definition to variable `storageLayout`

feat: add type definition

---

docs/source/getting-started.rst

Updated documentation to include multiple compiler support in hardhat config file.
- Fixes [#23](https://app.dework.xyz/smock/main-project-3127?taskId=602e8d6f-857e-4a22-90ed-d4d917027dff)
- Fixes #108

chore: multiple compiler support in hardhat config

---

.github/CODEOWNERS

build: codeowners

---

package.json

chore: v2.3.5

---

docs/source/getting-started.rst

docs: added matchers
